services:
  lavalink:
    # pin the image version to Lavalink v4 and use the alpine variant for a smaller image size
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - YT_OAUTH_TOKEN=${YT_OAUTH_TOKEN}
    volumes:
      - ./application.yaml:/opt/Lavalink/application.yaml
    networks:
      - lavalink
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers, keep in mind this will expose your lavalink to the internet
      # - "2333:2333"
      # if you want to restrict access to localhost only
      - "127.0.0.1:2333:2333"
  bot:
    image: andrewromanyk/el_nino:0.0.1
    container_name: el_nino
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LAVALINK_ENDPOINT=lavalink:2333
    depends_on:
      - lavalink
    networks:
      - lavalink
networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink